/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
import Quantity from './Quantity'

function o(keys: number[], dupe: number[], obj?: {[key: number]: number[]}) {
    obj = obj ?? {}
    for (let k of keys) {
        obj[k] = dupe
    }
    return obj
}
let $V0: number[] = [1,7]
let $V1: number[] = [1,9]
let $V2: number[] = [1,10]
let $V3: number[] = [1,11]
let $V4: number[] = [1,13]
let $V5: number[] = [1,14]
let $V6: number[] = [1,5,10,11,25]
let $V7: number[] = [1,17]
let $V8: number[] = [1,5,10,11,12,13,14,25]
let $V9: number[] = [1,5,10,11,12,13,14,15,16,25]
let $Va: number[] = [1,5,10,11,12,13,25];

function splitString(str: string, delimiter: string) {
    let result: string[] = []
    let pattern =string.format("([^%s]+)", delimiter)
    string.gsub(str, pattern, (...matches) => {
        result.push(matches[0])
        return undefined as unknown as string
    })
    return result.length != 0 ? result : undefined
}

type YY_State = {

}

type YYLoc = {
    first_line: number
    last_line: number
    first_column: number
    last_column: number
    range: [number, number]
}

type YACC_State = {
    yy: YY_State
    yylloc: YYLoc
    yyleng: number
    yytext: string
    yylineno: number

    match: string
    matches: string[]
    matched: string
    offset: number
    conditionStack: string[]

    _more: boolean
    _input: string
    done: boolean
}



/* generated by jison-lex 0.3.4 */
class Lexer {
    EOF = 1


    conditionStack: string[] = []

    match: string = ""
    matches: string[] = []
    matched: string = ""
    offset: number = 0
    last_line: number = 0

    _input: string = ""
    _backtrack: boolean = false
    _more: boolean = false
    done: boolean = false

    yy: YY_State = {}
    yylloc: YYLoc
    yyleng: number
    yytext: string
    yylineno: number

    options: {
        ranges?: boolean
        flex?: boolean
        backtrack_lexer?: boolean
    } = {}

    static parseError(str: string, hash: any) {
        Parser.parseError(str, hash);
    }
    
    constructor() {
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0,
            range: [0, 0]
        }
        
        this.yyleng = 0
        this.yytext = ""
        this.yylineno = 0
    }

// resets the lexer, sets new input
    setInput(input: string, yy: YY_State) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0,
            range: [0, 0]
        };
        if (this.options.ranges) {
            this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
    }

// consumes and returns one char from the input
    input() {
        let ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        // FIXME: REGEX (DONE?)
        let lines = splitString(ch, "\n");
        if (lines !== undefined) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    }

// unshifts one char (or a string) into the input
    unput(ch: string) {
        let len = ch.length;
        // FIXME: REGEX (DONE?)
        let lines = splitString(ch, "\n");

        this._input = ch + this._input;
        this.yytext = this.yytext.substring(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        // FIXME: REGEX (DONE?)
        let oldLines = splitString(this.match, "\n");
        this.match = this.match.substring(0, this.match.length - 1);
        this.matched = this.matched.substring(0, this.matched.length - 1);

        if (lines != undefined && lines.length - 1 !== 0) {
            this.yylineno -= lines.length - 1;
        }
        let r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines != null && oldLines != null ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                + oldLines[oldLines.length - lines.length].length - lines[0].length : this.yylloc.first_column - len,
            range: [0, 0]
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[1], r[1] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    }

// When called from action, caches matched text and appends it on next action
    more() {
        this._more = true;
        return this;
    }

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
    reject() {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return Lexer.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    }

// retain first n characters of the match
    less(n: number) {
        this.unput(this.match.slice(n));
    }

// displays already matched input, i.e. for error messages
    pastInput() {
        let past = this.matched.substring(0, this.matched.length - this.match.length);
        // FIXME: REGEX (DONE?)
        return `${past.length > 20 ? '...' : ''}${string.gsub(past.substr(-20), "\n", "")[0]}`;
    }

// displays upcoming input, i.e. for error messages
    upcomingInput(): string {
        let next = this.match;
        if (next.length < 20) {
            next += this._input.substring(0, 20 - next.length);
        }
        // FIXME: REGEX (DONE?)
        return string.gsub(next.substring(0, 20) + (next.length > 20 ? '...' : ''), "\n", "")[0];
    }

// displays the character position where the lexing error occurred, i.e. for error messages
    showPosition(): string {
        let pre = this.pastInput();
        let c = string.rep("-", pre.length + 1);
        return `${pre + this.upcomingInput()}\n${c}^`;
    }

// test the lexed token: return FALSE when not a match, otherwise return token
    test_match(match: string[], indexed_rule: number) {
        let token,
            lines,
            backup: YACC_State | undefined;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    ...this.yylloc
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: [...this.conditionStack],
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = [...this.yylloc.range];
            }
        }

        $log_trace!(serpent.line(match))
        // FIXME: REGEX (DONE?)
        lines = splitString(match[0], "\n")
        if (lines !== undefined) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines !== undefined ?
                lines[lines.length - 1].length - (lines[lines.length - 1] === "\n" ? 1 : 0) :
                this.yylloc.last_column + match[0].length,
            range: [0, 0]
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction(this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            if (backup != undefined) {
                for (let k in backup) {
                    // @ts-ignore
                    this[k] = backup[k];
                }
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    }

// return next match in input
    next() {
        if (this.done) {
            return this.EOF;
        }
        if (this._input == undefined) {
            this.done = true;
            this._input = ""
        }

        let token,
            match: string[] | undefined,
            tempMatch: string[] | undefined,
            index: number = 0;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        let rules = this._currentRules();
        for (let i = 0; i < rules.length; i++) {
            // FIXME: REGEX
            tempMatch = [...string.match(this._input, this.rules[rules[i]])];
            $log_trace!(`Matching: ${serpent.line(this.rules[rules[i]])}; '${this._input}' => ${serpent.line(tempMatch)}`)
            if(tempMatch.length == 0) tempMatch = undefined
            if (tempMatch != undefined && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false as unknown as string[];
                        // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            $log_trace!(`Matched: ${serpent.line(match)}`)
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return Lexer.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    }

// return next match that has a token
    lex(): any {
        let r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    }

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
    begin(condition: string) {
        this.conditionStack.push(condition);
    }

// pop the previously active lexer condition state off the condition stack
    popState() {
        let n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    }

// produce the lexer rule set which is active for the currently active lexer condition state
    _currentRules(): number[] {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1] != undefined) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    }

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
    topState(n: number) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    }

// alias for begin(condition)
    pushState(condition: string) {
        this.begin(condition);
    }

// return the number of states currently on the stack
    stateStackSize() {
        return this.conditionStack.length;
    }
    
    performAction(yy: YY_State, yy_: Lexer, $avoiding_name_collisions: number, YY_START: string): any | undefined {
        let YYSTATE = YY_START;
        switch ($avoiding_name_collisions) {
            case 0:/* skip whitespace */
                break;
            case 1:return 19
            case 2:return 12
            case 3:return 13
            case 4:return 11
            case 5:return 10
            case 6:return 15
            case 7:return 16
            case 8:return 14
            case 9:return 17
            case 10:return 25
            case 11:return 5
            case 12:return 20
        }
    }

    // FIXME: REGEX
    rules = ["^(%s+)", "^(%d+%.?%d*)", "^(%*)", "^(%/)", "^(%-)", "^(%+)", "^(%^)", "^(%!)", "^(%%)", "^(%()", "^(%))", "^$", "^(%a*)"]

    conditions: any = {
        "INITIAL": {
            "rules": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            "inclusive": true
        }
    }
}

class Parser {
    static trace(str: string) {
    }

    constructor() {
        this.yy = {};
    }

    $: any

    yy = {}
    symbols_: { [k: string]: number } = {
        "error": 2,
        "expressions": 3,
        "AdditiveExpression": 4,
        "EOF": 5,
        "unused__exp": 6,
        "factor": 7,
        "exp": 8,
        "partial_exp": 9,
        "PLUS": 10,
        "MINUS": 11,
        "TIMES": 12,
        "DIVIDE": 13,
        "MODULO": 14,
        "POWER": 15,
        "FACTORIAL": 16,
        "LPAREN": 17,
        "exp[RPAREN]": 18,
        "NUMBER": 19,
        "IDENTIFIER": 20,
        "MultiplicativeExpression": 21,
        "ExponentialExpression": 22,
        "UnaryExpression": 23,
        "PrimaryExpression": 24,
        "RPAREN": 25,
        "$accept": 0,
        "$end": 1
    }
    terminals_: { [k: number]: string } = {
        2: "error",
        5: "EOF",
        8: "exp",
        10: "PLUS",
        11: "MINUS",
        12: "TIMES",
        13: "DIVIDE",
        14: "MODULO",
        15: "POWER",
        16: "FACTORIAL",
        17: "LPAREN",
        18: "exp[RPAREN]",
        19: "NUMBER",
        20: "IDENTIFIER",
        25: "RPAREN"
    }

    productions_: (number | number[])[] = [0, [3, 2], [3, 1], [6, 1], [6, 3], [6, 3], [6, 3], [6, 3], [6, 3], [6, 3], [6, 3], [6, 2], [6, 2], [6, 2], [9, 1], [9, 1], [9, 1], [9, 1], [9, 1], [9, 1], [7, 2], [7, 1], [7, 1], [4, 1], [4, 3], [4, 3], [4, 3], [4, 3], [21, 1], [21, 3], [21, 3], [21, 3], [21, 3], [21, 3], [21, 3], [22, 1], [22, 3], [22, 3], [23, 1], [23, 2], [23, 2], [24, 1], [24, 3]]
    performAction(yytext: string, yyleng: number, yylineno: number, yy: any, yystate: any /* action[1] */, vstack: any[] /* vstack */, _$: any /* lstack */): Quantity | undefined {
        /* this == l */
        let $$: Quantity[] = vstack
        let $0 = $$.length - 1
        switch (yystate) {
            case 1:
                $log_trace!("EOF:\t" + $$[$0-1].toString());
                return $$[$0-1];
            case 2:
                $log_trace!("end:\t" + $$[$0].toString());
                return $$[$0];
            case 4: case 26: case 27: case 32: case 33: case 34: case 37:
                this.$ = $$[$0-2];
                break;
            case 5: case 24:
                this.$ = $$[$0-2].add($$[$0]);
                break;
            case 6: case 25:
                this.$ = $$[$0-2].sub($$[$0]);
                break;
            case 7: case 29:
                this.$ = $$[$0-2].mul($$[$0]);
                break;
            case 8: case 30:
                this.$ = $$[$0-2].div($$[$0]);
                break;
            case 9: case 31:
                this.$ = $$[$0-2].mod($$[$0]);
                break;
            case 10: case 36:
                this.$ = $$[$0-2].pow($$[$0]);
                break;
            case 11: case 39:
                this.$ = $$[$0-1].factorial();
                break;
            case 12: case 40:
                this.$ = $$[$0].mul(-1);
                break;
            case 13: case 19:
                this.$ = $$[$0];
                break;
            case 20:
                this.$ = Quantity.fromNumberWithUnit(Number($$[$0-1]), vstack[$0]);
                break;
            case 21:
                this.$ = Quantity.fromNumber(Number(vstack[$0]));
                break;
            case 22:
                this.$ = Quantity.fromUnit(vstack[$0]);
                break;
            case 42:
                this.$ = $$[$0-1];
                break;
        }
        return undefined;
    }

    table: {[key: number]: number | number[]}[] = [
        {3:1,4:2,7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:3,22:4,23:5,24:6},
        {1:[3]},
        {1:[2,2],5:[1,12],10:$V4,11:$V5},
        o($V6,[2,23],{12:[1,15],13:[1,16],14:$V7}),
        o($V8,[2,28]),
        o($V8,[2,35],{15:[1,18],16:[1,19]}),
        o($V9,[2,38]),{7:8,11:$V0,17:$V1,19:$V2,20:$V3,23:20,24:6},
        o($V9,[2,41]),{4:21,7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:3,22:4,23:5,24:6},
        o($V9,[2,21],{20:[1,22]}),
        o($V9,[2,22]),
        {1:[2,1]},
        {4:23,5:[1,24],7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:3,22:4,23:5,24:6},
        {4:25,5:[1,26],7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:3,22:4,23:5,24:6},
        {5:[1,28],7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:27,22:4,23:5,24:6},
        {5:[1,30],7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:29,22:4,23:5,24:6},
        {5:[1,32],7:8,11:$V0,17:$V1,19:$V2,20:$V3,21:31,22:4,23:5,24:6},
        {5:[1,34],7:8,11:$V0,17:$V1,19:$V2,20:$V3,22:33,23:5,24:6},
        o($V9,[2,39]),
        o($V9,[2,40]),
        {10:$V4,11:$V5,25:[1,35]},
        o($V9,[2,20]),
        o($V6,[2,24]),
        o($V6,[2,26]),
        o($V6,[2,25]),
        o($V6,[2,27]),
        o($Va,[2,29],{14:$V7}),
        o($V8,[2,32]),
        o($Va,[2,30],{14:$V7}),
        o($V8,[2,33]),
        o($Va,[2,31],{14:$V7}),
        o($V8,[2,34]),
        o($V8,[2,36]),
        o($V8,[2,37]),
        o($V9,[2,42])
    ]
    defaultActions = {12:[2,1]}

    static parseError(this: void, str: string, hash: any) {
        if (hash?.recoverable) {
            Parser.trace(str);
        } else {
            let error: any = new Error(str);
            error.hash = hash;
            throw error;
        }
    }
    parse(this: any, input: string) {
        let self = this

        let stack: number[] = [0], tstack: any[] = []
        let vstack: (string | null)[] = [null], lstack:  YYLoc[] = []
        let table: {[p: number]: number | number[]}[] = this.table, yytext = ''
        let yylineno = 0, yyleng = 0, recovering = 0
        const TERROR = 2, EOF = 1;
        let args = [input];
        let lexer: Lexer = new Lexer();
        let sharedState: any = {yy: {}};
        for (let k in this.yy) {
            sharedState.yy[k] = this.yy[k];
        }
        lexer.setInput(input, sharedState.yy);
        sharedState.yy.lexer = lexer;
        sharedState.yy.parser = this;
        if (typeof lexer.yylloc == 'undefined') {
            lexer.yylloc = {
                first_line: 1,
                first_column: 0,
                last_line: 1,
                last_column: 0,
                range: [0, 0]
            };
        }
        let yyloc = lexer.yylloc;
        lstack.push(yyloc);
        let ranges = lexer.options && lexer.options.ranges;

        function popStack(n: number) {
            stack.length = stack.length - 2 * n;
            vstack.length = vstack.length - n;
            lstack.length = lstack.length - n;
        }
        let lex = function () {
            let token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
        let symbol = undefined, preErrorSymbol, state, action: number[], a, r, yyval: {
            $?: string | null
            _$?: YYLoc
        } = {}, p, len: number, newState: number, expected;
        while (true) {
            state = stack[stack.length - 1];
            if (this.defaultActions[state]) {
                action = this.defaultActions[state];
            } else {
                if (symbol === undefined) {
                    symbol = lex();
                }
                let tmp  = table[state] && table[state][symbol]
                action = typeof tmp == "number" ? [tmp] : tmp;
            }
            $log_trace!(`state: ${state} => ${serpent.line(action)}`)
            if (typeof action === 'undefined' || !action.length || !action[1]) {
                let errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p as unknown as number > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition !== undefined) {
                    errStr = `Parse error on line ${yylineno + 1}:\n${lexer.showPosition()}\nExpecting ${expected.join(', ')}, got '${this.terminals_[symbol] || symbol}'`;
                } else {
                    errStr = `Parse error on line ${yylineno + 1}: Unexpected ${symbol === EOF ? 'end of input' : `'${this.terminals_[symbol] || symbol}'`}`;
                }
                Parser.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
            if (typeof action[0] != "number" && action.length > 1) {
                throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
            }
            $log_trace!(`============= Action ${action[1]} ============= `)
            switch (action[0]) {
                case 1:
                    $log_trace!(`stack << ${symbol} << ${action[2]}`)
                    stack.push(symbol);
                    vstack.push(lexer.yytext);
                    lstack.push(lexer.yylloc);
                    stack.push(action[1]);
                    symbol = null;
                    if (!preErrorSymbol) {
                        yyleng = lexer.yyleng ?? 0;
                        yytext = lexer.yytext ?? "";
                        yylineno = lexer.yylineno ?? 0;
                        yyloc = lexer.yylloc;
                        if (recovering > 0) {
                            recovering--;
                        }
                    } else {
                        symbol = preErrorSymbol;
                        preErrorSymbol = null;
                    }
                    break;
                case 2:
                    len = (this.productions_[action[1] + 1] as number[])[1];
                    let last_item = lstack[lstack.length - 1]
                    let pord_item = lstack[lstack.length - (len || 1)]
                    $log_trace!(`(${len}; ${action[1]}) #${stack.length} ${serpent.line(stack)}`)
                    yyval.$ = vstack[vstack.length - len];
                    yyval._$ = {
                        first_line: pord_item?.first_line ?? 0,
                        last_line: last_item?.last_line ?? 0,
                        first_column: pord_item?.first_column ?? 0,
                        last_column: last_item?.last_column ?? 0,
                        range: [
                            pord_item.range[0],
                            last_item.range[1]
                        ]
                    };

                    let func = this.performAction
                    // change 'this' to 'yyval'
                    r = func(yyval, yytext, yyleng, yylineno, sharedState.yy,
                        action[1], vstack, lstack, args);
                    if (typeof r !== 'undefined') {
                        return r;
                    }
                    if (len > 0) {
                        stack = stack.slice(0, -1 * len * 2);
                        vstack = vstack.slice(0, -1 * len);
                        lstack = lstack.slice(0, -1 * len);
                    }
                    let prod = (this.productions_[action[1] + 1] as number[])[0]
                    stack.push(prod);
                    vstack.push(yyval.$);
                    lstack.push(yyval._$);
                    $log_trace!(`Stack: ${serpent.line(stack)} Vstack: ${serpent.line(vstack)} Lstack: ${serpent.line(lstack)}`)
                    let s_len = stack.length
                    let a = stack[s_len - 2]
                    newState = table[a][prod] as number;
                    $log_trace!(`New state: ${newState}  table[${a}][${prod}]`)
                    stack.push(newState);
                    break;
                case 3:
                    return true;
            }
        }
        return true;
    }
};

let math = new Parser();

function parse(str: string) {
    return math.parse(str)
}

export default Parser
export {
    math,
    parse
}